bug fix + README

diff --git a/kubech b/kubech
--- a/kubech
+++ b/kubech
@@ -19,7 +19,7 @@ kubech () {
   cat <<EOF
 NOTE:
   - The command "kubech" is just a meta for other commands. So kubech does nothing by itself.
-  - Also short names like "kchc/kchn/kchu" are available.
+  - Also short names like "kctx/kns/kundo" are available.
 
 VARS:
   KUBECONFIG_SRC_DIR  : Set directory with extra kubectl config files to read in kubech commands.
@@ -32,11 +32,11 @@ VARS:
                         Default: "${KUBECONFIG_DEST_DIR}"
 
 USAGE:
-  kubechc             : List all contexts
-  kubechc <CONTEXT>   : Switch to context <CONTEXT>
-  kubechn             : List all namespaces
-  kubechn <NAMESPACE> : Switch to namespace <NAMESPACE>
-  kubechu             : Unset the active context. This is just a safty net
+  kctx                : List all contexts
+  kctx <CONTEXT>      : Switch to context <CONTEXT>
+  kns                 : List all namespaces
+  kns <NAMESPACE>     : Switch to namespace <NAMESPACE>
+  kundo               : Unset the active context. This is just a safty net
                         to avoid applying config by mistake to the wrong cluster.
 EOF
 }
@@ -50,7 +50,6 @@ mkdir -p "${KUBECONFIG_SRC_DIR}" "${KUBECONFIG_DEST_DIR}"
 chmod 744 "${KUBECONFIG_SRC_DIR}" "${KUBECONFIG_DEST_DIR}"
 
 
-#
 # Handeling Kube config files.
 _kubeconfig_files () {
     if [ -d "${KUBECONFIG_SRC_DIR}" ]; then
@@ -69,7 +68,10 @@ _kubeconfig_files () {
     echo "${KUBECONFIG_FILES}${KUBECONFIG_ORIG}"
 }
 
-_kube_config () {
+
+# Change value of KUBECONFIG variable
+# if $1 existe, append $1 to prefix of KUBECONFIG
+_kubeconfig_append () {
     KUBECONFIG_DEFAULT="$(_kubeconfig_files)"
     if [ -n "${1}" ]; then
         if [[ "${KUBECONFIG}" == "${KUBECONFIG_ACTIVE}" ]]; then
@@ -89,26 +91,25 @@ _kube_config () {
     fi
 }
 
-
-#
-# Generate kubectl config for a single context.
-_kubechg () {
-    kube_context="${1}"
-    kube_namespace="${2:-default}"
+# Create a temporary kubeconfig file
+_kubeconfig_tmp () {
+    local kube_context="${1}"
+    local kube_namespace="${2:-default}"
 
     # create tmp variable to sanitize kube_context's name if it contains / or :
-    kube_context_tmp=${kube_context}
+    local kube_context_tmp=${kube_context}
     if [[ ${kube_context_tmp} =~ "/" || ${kube_context_tmp} =~ ":" ]]; then
         kube_context_tmp=${kube_context_tmp//\//@}
         kube_context_tmp=${kube_context_tmp//:/_}
     fi
 
-    kubeconfig_file="${kube_context_tmp}-${kube_namespace}"
+    local kubeconfig_file="${kube_context_tmp}-${kube_namespace}"
 
     touch "${KUBECONFIG_DEST_DIR}/${kubeconfig_file}"
     chmod 600 "${KUBECONFIG_DEST_DIR}/${kubeconfig_file}"
 
-    KUBECONFIG="$(_kube_config)"    \
+    # write contents of first kubeconfig in KUBECONFIG to a tmp kubeconfig file
+    KUBECONFIG="$(_kubeconfig_append)"    \
     kubectl config view             \
         --minify                    \
         --flatten                   \
@@ -116,52 +117,63 @@ _kubechg () {
         "${KUBECONFIG_DEST_DIR}/${kubeconfig_file}"
 }
 
+# Switch kube context
+kctx () {
+    local kube_context="${1}"
+    local kube_namespace="${2:-default}"
 
-#
-# Change kubectl context.
-kubechc () {
-    kube_context="${1}"
-    kube_namespace="${2:-default}"
+    # create tmp variable to sanitize kube_context's name if it contains / or :
+    local kube_context_tmp=${kube_context}
+    if [[ ${kube_context_tmp} =~ "/" || ${kube_context_tmp} =~ ":" ]]; then
+        kube_context_tmp=${kube_context_tmp//\//@}
+        kube_context_tmp=${kube_context_tmp//:/_}
+    fi
+
+    local kubeconfig_file="${kube_context_tmp}-${kube_namespace}"
 
     if [[ -n "${kube_context}" ]]; then
-        _kubechg "${kube_context}" "${kube_namespace}"
-        _kube_config "${KUBECONFIG_DEST_DIR}/${kube_context}-${kube_namespace}"
-        # kubectl config current-context
+        # Only switch context if context exists.
+        if echo "$(kubectl config get-contexts --no-headers=true -o name)" | grep -qE "^${kube_context}$"; then
+            _kubeconfig_tmp "${kube_context}" "${kube_namespace}"
+            if [[ "${kube_context}" != "$(kubectl config current-context)" ]]; then
+                echo "Switched to context \"${kube_context}\"."
+            fi
+
+            _kubeconfig_append "${KUBECONFIG_DEST_DIR}/${kubeconfig_file}"
+        else
+            echo "error: no context exists with name \"${kube_context}\"."
+            return 1 2>/dev/null
+            exit 1
+        fi
     else
-        KUBECONFIG=$(_kube_config) kubectl config get-contexts --no-headers=true -o name
+        KUBECONFIG=$(_kubeconfig_append) kubectl config get-contexts --no-headers=true -o name
     fi
 }
 
-alias kctx='kubechc'
-
-
-#
-# Change kubectl namespace
-kubechn () {
-    kube_namespace="${1:-default}"
-    kube_namespace_all=$(kubectl get namespaces -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')
+# Switch namespace
+kns () {
+    local kube_namespace="${1:-default}"
+    local kube_namespace_all=$(kubectl get namespaces -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')
 
     if [[ -n ${1} ]]; then
         # Only switch namespace if it exists.
         if echo "${kube_namespace_all}" | grep -qE "^${kube_namespace}$"; then
-            kubechc "$(kubectl config current-context)" "${kube_namespace}"
+            kctx "$(kubectl config current-context)" "${kube_namespace}"
             kubectl config set-context --current --namespace="${kube_namespace}"
-            echo "Switched to namespace \"${kube_namespace}\""
+            echo "Switched to namespace \"${kube_namespace}\"."
         else
-            echo "The namespace \"${kube_namespace}\" doesn't exist"
+            echo "error: no namespace exists with name \"${kube_namespace}\"."
+            return 1 2>/dev/null
+            exit 1
         fi
     else
         echo "${kube_namespace_all}"
     fi
 }
 
-alias kns='kubechn'
-
-
-#
 # Unset the active context.
-kubechu () {
+kundo () {
     kubectl config unset current-context
 }
 
-alias kchu='kubechu'
+
